### ISSUE TITLE
关于收集方法

### ISSUE THREAD

**Issue by wanhang189** [burukeYou/JDFrame#16]
收集器需要能直接收集map<string,obj>,
分组收集到map<string,list<obj>>,
类似于jdk1.8的常用收集器，而不是需要FI2

**Comment by burukeYou** [comment]
可以再调用Fraame.toMap方法进行转换。 也可以直接Frame.stream().collect(Collector.toMap))去收集转换(不推荐代码太啰嗦)。 后续再加一个自动toMap的方法不必指定map字段。 如果是FI2或者F3等矩阵列表可以自动map
