### ISSUE TITLE
distinct问题

### ISSUE THREAD

**Issue by LeonemZhang** [burukeYou/JDFrame#7]
`distinct(Comparator<T> comparator)`方法最终使用TreeSet来实现过滤，考虑如下去重场景：

如果名称相同，只保留时间最新的那个；名称不同认为是不同对象

那比较器应该定义如下：
```
(o1, o2) -> {
    final int nameCompare = o1.getName().compareTo(o2.getName());
    if (nameCompare != 0) {
	return nameCompare;
    }
    return o2.getTime().compareTo(o1.getTime());
}
```

当比较器返回0时认为对象相同，观察上述比较器发现：只要名称相同且时间不同，比较器就会返回非0值，最终两个对象都会被存下来。

所以目前实现这个需求只能这么写：
```         
frame.sortDesc(Obj::getTime())
         .distinct(Obj::getName());
```
让时间新的对象先进set，后面名称相同的就会因为重复被过滤掉

考虑是不是搞一个两function的distinct函数，一个传入map的new方法，另一个传入computeIfPresent

**Comment by burukeYou** [comment]
> `distinct(Comparator<T> comparator)`方法最终使用TreeSet来实现过滤，考虑如下去重场景：
> 
> 如果名称相同，只保留时间最新的那个；名称不同认为是不同对象
> 
> 那比较器应该定义如下：
> 
> ```
> (o1, o2) -> {
>     final int nameCompare = o1.getName().compareTo(o2.getName());
>     if (nameCompare != 0) {
> 	return nameCompare;
>     }
>     return o2.getTime().compareTo(o1.getTime());
> }
> ```
> 
> 当比较器返回0时认为对象相同，观察上述比较器发现：只要名称相同且时间不同，比较器就会返回非0值，最终两个对象都会被存下来。
> 
> 所以目前实现这个需求只能这么写：
> 
> ```
> frame.sortDesc(Obj::getTime())
>          .distinct(Obj::getName());
> ```
> 
> 让时间新的对象先进set，后面名称相同的就会因为重复被过滤掉
> 
> 考虑是不是搞一个两function的distinct函数，一个传入map的new方法，另一个传入computeIfPresent

如果重复，然后从重复的元素里选一个出来确实有一定的通用性后续会考虑提供以下api。 
`distinct(Function, (list) -> {list.get(0)});`
增加一个list的回调函数，让开发者去自定义如何从重复的元素列表里选一个。

至于两个两function的distinct函数就没必要的没如果要多字段去重复，直接distinct多次或者使用Comparator.thenComparing

**Comment by burukeYou** [comment]
已新增特性。 见0.1.0版本及以上
