### ISSUE TITLE
不支持jdk 17么，编译报错

### ISSUE THREAD

**Issue by eaglebetter** [burukeYou/JDFrame#8]

**Comment by burukeYou** [comment]
可以看看错误信息吗

**Comment by eaglebetter** [comment]
没注意，pom文件有设置编译版本，改下好像可以了。

**Comment by eaglebetter** [comment]
![image](https://github.com/burukeYou/JDFrame/assets/5466381/dcaf298e-23a0-499c-b6a3-2bfd5a464688)

**Comment by eaglebetter** [comment]
用jdk17运行test下用例不行。

**Comment by burukeYou** [comment]
> ![image](https://private-user-images.githubusercontent.com/5466381/332676451-dcaf298e-23a0-499c-b6a3-2bfd5a464688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNTk5MzcsIm5iZiI6MTcxNjM1OTYzNywicGF0aCI6Ii81NDY2MzgxLzMzMjY3NjQ1MS1kY2FmMjk4ZS0yM2EwLTQ5OWMtYjZhMy0yYmZkNWE0NjQ2ODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMDYzMzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2Q0YzM4NDUzMzgxNzg0ODM4MDUzZmIxMDBhMTRiNDUwZTA2MGMwNTAyMGYwNDA2NmE3ZjU2YmQ0NzViMGY5OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._MSZ2uem4sgc75xyLz7SLfxy4RP4BcjAcWj44j6zkmE)

我优化了下，你换0.0.5版本试下

**Comment by eaglebetter** [comment]
大部分可以了还有个方法看起来异常：
![1716432176412](https://github.com/burukeYou/JDFrame/assets/5466381/1d116e44-0280-4efd-8457-b5f41bfeb83e)
