### ISSUE TITLE
关于排序

### ISSUE THREAD

**Issue by taowater** [burukeYou/JDFrame#9]
![image](https://github.com/burukeYou/JDFrame/assets/38535244/427e5400-2ee7-47f9-bb3b-cfdaa2c04626)
关于此处的多维排序，stream的多次调用排序方法，最终的排序结果并不是符合直觉的多维排序，而是粗暴地依次按当前元素多次排序
个人也有对于流的增强库实现，关于多维排序这块，有一种处理与作者讨论
![image](https://github.com/burukeYou/JDFrame/assets/38535244/264cbaf1-2822-4baf-bbb9-08ab9ea45757)
核心逻辑为使用Comparator::thenComparing，又看到作者也有类似Sorter的概念
阅读代码中，另附拙库链接就正方家：
https://github.com/taowater/ztream

**Comment by burukeYou** [comment]
是的，这里例子写错了，多维排序应该使用Compartor入参的排序。 
如果只是按照多个字段排序， 可以使用Sorter去指定，它本身也是Compartor只是可以更加语义化的使用。 多字段排序可以写:          `SDFrame.read(studentList).sortAsc(Sorter.sortDescBy(Student::getAge).sortAsc(Student::getLevel));`   
原生Compartor更推荐存在自定义的排序逻辑而非使用字段排序才使用。 
哈哈你也有Sorter，居然名字也一样。

**Comment by taowater** [comment]
> 是的，这里例子写错了，多维排序应该使用Compartor入参的排序。 如果只是按照多个字段排序， 可以使用Sorter去指定，它本身也是Compartor只是可以更加语义化的使用。 多字段排序可以写: `SDFrame.read(studentList).sortAsc(Sorter.sortDescBy(Student::getAge).sortAsc(Student::getLevel));` 原生Compartor更推荐存在自定义的排序逻辑而非使用字段排序才使用。 哈哈你也有Sorter，居然名字也一样。

这种写法我的实现和你一样一样的，只是api名字不一样，主要是jdk原生stream 的体验太差了，关于窗口这块没有想过，向大佬学习
